// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVUV59HDmSnol3KMgRS9_DAIG2MFgbf3U',
    appId: '1:633890575719:web:8d86f2efe9539364d34bc2',
    messagingSenderId: '633890575719',
    projectId: 'groupmoneycollection',
    authDomain: 'groupmoneycollection.firebaseapp.com',
    storageBucket: 'groupmoneycollection.firebasestorage.app',
    measurementId: 'G-KTKSY3KC82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDup0VKk8m9ts34ancsne6O0JTEuTp0f8s',
    appId: '1:633890575719:android:d2e80c75d64bf4c7d34bc2',
    messagingSenderId: '633890575719',
    projectId: 'groupmoneycollection',
    storageBucket: 'groupmoneycollection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-dy_BanaHcE-Gvu4FjK5A4zN5d78cfQ',
    appId: '1:633890575719:ios:bd2a78d8b50dc497d34bc2',
    messagingSenderId: '633890575719',
    projectId: 'groupmoneycollection',
    storageBucket: 'groupmoneycollection.firebasestorage.app',
    iosBundleId: 'com.example.moneyCollection2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-dy_BanaHcE-Gvu4FjK5A4zN5d78cfQ',
    appId: '1:633890575719:ios:bd2a78d8b50dc497d34bc2',
    messagingSenderId: '633890575719',
    projectId: 'groupmoneycollection',
    storageBucket: 'groupmoneycollection.firebasestorage.app',
    iosBundleId: 'com.example.moneyCollection2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVUV59HDmSnol3KMgRS9_DAIG2MFgbf3U',
    appId: '1:633890575719:web:f15b666d09b3c181d34bc2',
    messagingSenderId: '633890575719',
    projectId: 'groupmoneycollection',
    authDomain: 'groupmoneycollection.firebaseapp.com',
    storageBucket: 'groupmoneycollection.firebasestorage.app',
    measurementId: 'G-MN8G2LB6LG',
  );

}